# -*- coding: utf-8 -*-
"""komdigi_hoaks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQpM2t9zL4YU5Lm1aXO19rhE8qQ28fLi
"""

import pandas as pd

# Memuat dataset
df = pd.read_csv('komdigi_hoaks.csv')

# Melihat data teratas
print(df.head())
print(df.info())

# Memeriksa jumlah data kosong di setiap kolom
print(df.isnull().sum())

# Menghapus baris yang teks utamanya kosong
df = df.dropna(subset=['title', 'body_text'])

# Menampilkan 5 baris yang kolom 'main_image_url'-nya kosong
baris_kosong_gambar = df[df['main_image_url'].isnull()]
print(baris_kosong_gambar[['id', 'title', 'main_image_url']].head())

import re

def clean_text(text):
    # 1. Mengubah teks menjadi huruf kecil semua (Lowercasing)
    text = text.lower()

    # 2. Menghapus tag HTML (jika masih terbawa di body_text)
    text = re.sub(r'<.*?>', '', text)

    # 3. Menghapus URL/Link
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # 4. Menghapus karakter khusus, angka, dan tanda baca
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # 5. Menghapus spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Menerapkan fungsi pembersihan ke kolom title dan body_text
df['clean_title'] = df['title'].apply(clean_text)
df['clean_body'] = df['body_text'].apply(clean_text)



# Menghapus kata umum/stopwords
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopword_remover = factory.create_stop_word_remover()

def remove_stopwords(text):
    return stopword_remover.remove(text)

df['clean_body'] = df['clean_body'].apply(remove_stopwords)

# Stemming
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory_stem = StemmerFactory()
stemmer = factory_stem.create_stemmer()

df['stemmed_body'] = df['clean_body'].apply(lambda x: stemmer.stem(x))

# Memilih kolom-kolom yang sudah bersih saja untuk disimpan
df_ready = df[['id', 'clean_title', 'stemmed_body', 'category']]

# Menyimpan ke file baru
df_ready.to_csv('drive/MyDrive/komdigi_hoaks_clean.csv', index=False)
print("Preprocessing selesai! Data disimpan ke 'drive/MyDrive/komdigi_hoaks_clean.csv'")

# Hasil pre-processing, menampilkan data teratas
print(df_ready.head())
print(df_ready.info())

df_ready['text'] = (
    df_ready['clean_title'].fillna('') +
    " " +
    df_ready['stemmed_body'].fillna('')
)

print(df_ready[['text', 'category']].head())

"""# **PENGOLAHAN DATASET**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# 1. Menentukan input (X) dan target label (y)
# 'stemmed_body' adalah kolom teks bersih hasil preprocessing sebelumnya
# 'topics' atau 'category' digunakan sebagai kolom target prediksi
X = df['stemmed_body']
y = df['topics'] # menyesuaikan kolom target

# 2. Membagi data menjadi Data training dan Data testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Proses Ekstraksi menggunakan TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Maksimal 5000 kata terpenting
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)
# --- SIMULASI DATA (Gunakan kolom 'stemmed_body' dari dataset Anda) ---
# Kita ambil sampel 5 baris pertama agar tampilan hasilnya mudah dibaca dan tidak terlalu panjang
sampel_teks = df['stemmed_body'].head(5)

# 1. Inisialisasi TF-IDF Vectorizer
# Kita batasi max_features=15 kata terpenting agar tabelnya tidak terlalu lebar saat ditampilkan
tfidf_vectorizer = TfidfVectorizer(max_features=15)

# 2. Proses Ekstraksi (Fit & Transform)
tfidf_matrix = tfidf_vectorizer.fit_transform(sampel_teks)


# =====================================================================
# KODE TAMBAHAN UNTUK MENAMPILKAN HASIL EKSTRAKSI TF-IDF
# =====================================================================

# A. Menampilkan Daftar Kata Unik (Vocabulary/Fitur) yang Ditemukan
fitur_kata = tfidf_vectorizer.get_feature_names_out()
print("=== 1. DAFTAR KATA KUNCI (FITUR) YANG BERHASIL DIEKSTRAK ===")
print(fitur_kata)
print("\n" + "="*60 + "\n")

# B. Mengubah Matriks TF-IDF menjadi Tabel DataFrame Agar Mudah Dibaca
df_hasil_tfidf = pd.DataFrame(data=tfidf_matrix.toarray(), columns=fitur_kata)

# Menambahkan kolom indeks dokumen untuk memperjelas barisnya
df_hasil_tfidf.insert(0, 'Dokumen_Ke', range(1, len(df_hasil_tfidf) + 1))

print("=== 2. TABEL MATRIKS BOBOT ANGKA TF-IDF ===")
print(df_hasil_tfidf.to_string(index=False))

# 4. Pemrosesan menggunakan Logistic Regression / SVM
model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

# 5. Hasil Pengolahan Data
y_pred = model.predict(X_test_tfidf)
print("Akurasi Model:", accuracy_score(y_test, y_pred))
print("\nLaporan Klasifikasi:\n", classification_report(y_test, y_pred))

"""### Kesimpulan
Konversi teks dari TF-IDF menghasilkan matriks berdimensi sangat tinggi, model SVM dan Logistic Regression sangat efektif dalam menangani jenis data spasial renggang (sparse matrix) tanpa mudah mengalami gejala overfitting. Sehingga menciptakan sistem pengolahan data yang ringan namun tetap menghasilkan akurasi yang sangat tinggi dalam mengklasifikasikan jenis-jenis hoaks dari dataset komdigi.

# **PENGOLAHAN DATASET MENGGUNAKAN MODEL LAIN**

### **SUPERVISED LEARNING**

**Decision tree**
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score

# 1. Menentukan Variabel Input (X) dan Target (y)
X = df['stemmed_body']
y = df['topics'] # Menargetkan kolom topics hoaks

# 2. Membagi Data menjadi Data Latih (80%) dan Data Uji (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Ekstraksi Fitur dengan TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# 4. Inisialisasi dan Pelatihan Model Decision Tree
# Penjelasan parameter penting:
# - max_depth=20: Membatasi kedalaman pohon agar tidak bercabang terlalu ekstrem (mencegah overfitting)
# - criterion='gini': Indikator untuk mengukur kualitas pemisahan cabang (bisa juga menggunakan 'entropy')
model_dt = DecisionTreeClassifier(max_depth=20, criterion='gini', random_state=42)
model_dt.fit(X_train_tfidf, y_train)

# 5. Prediksi dan Evaluasi Model
y_pred_dt = model_dt.predict(X_test_tfidf)

print("=== HASIL EVALUASI MODEL DECISION TREE ===")
print("Akurasi Model:", accuracy_score(y_test, y_pred_dt))
print("\nLaporan Klasifikasi:\n", classification_report(y_test, y_pred_dt))

"""**Random forest**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# 1. Menentukan Variabel Input (X) dan Target (y)
X = df['stemmed_body']
y = df['topics'] # Menargetkan kolom topics hoaks

# 2. Membagi Data menjadi Data Latih (80%) dan Data Uji (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Ekstraksi Fitur dengan TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# 4. Inisialisasi dan Pelatihan Model Random Forest
# Penjelasan parameter penting:
# - n_estimators=100: Membuat 100 pohon keputusan independen di dalam "hutan"
# - max_depth=20: Membatasi kedalaman setiap pohon agar komputasi tidak terlalu berat
# - n_jobs=-1: Menggunakan semua inti CPU komputer agar proses pelatihan lebih cepat
model_rf = RandomForestClassifier(n_estimators=100, max_depth=20, n_jobs=-1, random_state=42)
model_rf.fit(X_train_tfidf, y_train)

# 5. Prediksi dan Evaluasi Model
y_pred_rf = model_rf.predict(X_test_tfidf)

print("=== HASIL EVALUASI MODEL RANDOM FOREST ===")
print("Akurasi Model:", accuracy_score(y_test, y_pred_rf))
print("\nLaporan Klasifikasi:\n", classification_report(y_test, y_pred_rf))

"""**Naive bayes**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

# 1. Menentukan Variabel Input (X) dan Target (y)
X = df['stemmed_body']
y = df['topics'] # Menargetkan kolom topics hoaks

# 2. Membagi Data menjadi Data Latih (80%) dan Data Uji (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Ekstraksi Fitur dengan TF-IDF
# Naive Bayes bekerja sangat baik bahkan jika jumlah kata kunci (max_features) sangat besar
tfidf_vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# 4. Inisialisasi dan Pelatihan Model Naive Bayes
# Parameter alpha=1.0 adalah Laplace Smoothing untuk mencegah probabilitas bernilai 0
# jika ada kata baru yang belum pernah muncul di data latihan.
model_nb = MultinomialNB(alpha=1.0)
model_nb.fit(X_train_tfidf, y_train)

# 5. Prediksi dan Evaluasi Model
y_pred_nb = model_nb.predict(X_test_tfidf)

print("=== HASIL EVALUASI MODEL NAIVE BAYES ===")
print("Akurasi Model:", accuracy_score(y_test, y_pred_nb))
print("\nLaporan Klasifikasi:\n", classification_report(y_test, y_pred_nb))

"""### **UNSUPERVISED LEARNING**

**K-Means clustering**
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# 1. Menentukan Variabel Input (Hanya teks, tidak butuh target 'y')
X = df['body_text']

# 2. Ekstraksi Fitur dengan TF-IDF
# Untuk clustering, membatasi max_features membantu membuat hasil cluster lebih fokus
tfidf_vectorizer = TfidfVectorizer(max_features=1000)
X_tfidf = tfidf_vectorizer.fit_transform(X)

# 3. Inisialisasi dan Pelatihan Model K-Means
# Contoh: Kita ingin mengelompokkan data hoaks ini menjadi 5 tren/topik utama (n_clusters=5)
num_clusters = 5
model_kmeans = KMeans(n_clusters=num_clusters, init='k-means++', max_iter=300, random_state=42)
model_kmeans.fit(X_tfidf)

# 4. Memasukkan Hasil Cluster Kembali ke DataFrame Asli
df['cluster_label'] = model_kmeans.labels_


# =====================================================================
# KODE TAMBAHAN UNTUK MENAMPILKAN KATA KUNCI PER CLUSTER
# =====================================================================
print("=== HASIL K-MEANS CLUSTERING (KATA KUNCI TIAP KELOMPOK) ===\n")

# Mendapatkan koordinat pusat cluster (centroids) dan daftar kata dari TF-IDF
centroids = model_kmeans.cluster_centers_.argsort()[:, ::-1]
fitur_kata = tfidf_vectorizer.get_feature_names_out()

for i in range(num_clusters):
    print(f"--- Cluster {i+1} ---")
    # Mengambil 8 kata terpenting yang paling mendominasi cluster tersebut
    top_words = [fitur_kata[ind] for ind in centroids[i, :8]]
    print("Kata Kunci Dominan:", ", ".join(top_words))

    # Menampilkan jumlah dokumen yang masuk ke cluster ini
    jumlah_doc = len(df[df['cluster_label'] == i])
    print(f"Jumlah Berita Hoaks: {jumlah_doc} dokumen\n")

"""Logistic regression / SVM = 0,845
Decision tree = 0,81
Random forest = 0,848
Naive bayes = 0,848
"""
